class Qgis2JsonError(Exception): ...


class UnknownQgisTypeError(Qgis2JsonError): ...


class UnknownCrsSystemError(Qgis2JsonError): ...


class MissingParentError(Qgis2JsonError): ...


class UnknownVectorLayerDataproviderError(Qgis2JsonError): ...
