class Qgis2JsonError(Exception): ...


class UnknownQgisTypeError(Qgis2JsonError): ...


class UnknownCrsSystemError(Qgis2JsonError): ...


class MissingParentError(Qgis2JsonError): ...


class MissingFieldError(Qgis2JsonError): ...


class UnexpectedSchemaValueError(Qgis2JsonError): ...


class UnknownVectorLayerDataproviderError(Qgis2JsonError): ...


class InvalidCustomPropertyError(Qgis2JsonError): ...


class InvalidExtentError(Qgis2JsonError): ...
